In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.DataFrame({'x0':[2,1,1,1,1],'x1':[1,2,3,4,5],'x2':[2,3,4,5,6],'y':[4,6,8,10,12]})

In [4]:
df

x0  x1  x2   y
0   2   1   2   4
1   1   2   3   6
2   1   3   4   8
3   1   4   5  10
4   1   5   6  12

In [35]:
X=np.mat(df[['x0','x1','x2']].values)
Y=np.mat(df['y'].values.reshape(-1,1))

In [36]:
print(X)
print(Y)

[[2 1 2]
 [1 2 3]
 [1 3 4]
 [1 4 5]
 [1 5 6]]
[[ 4]
 [ 6]
 [ 8]
 [10]
 [12]]


In [9]:
#最小二乘法
theta=((X.T*X).I)*(X.T)*Y
theta

matrix([[ -9.91207116e-13],
        [ -7.10542736e-15],
        [  2.00000000e+00]])

In [50]:
(X.T*X).I

matrix([[  2.5,   5. ,  -4.5],
        [  5. ,  11.8, -10.4],
        [ -4.5, -10.4,   9.2]])

In [37]:
X1=np.mat(df[['x1','x2']].values)

In [13]:
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [14]:
X1

matrix([[1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 6]], dtype=int64)

In [38]:
#LinearRegression?
print(X1)
print(Y)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
[[ 4]
 [ 6]
 [ 8]
 [10]
 [12]]


In [39]:
ss=StandardScaler()
#X1=ss.fit_transform(X1)
lr=LinearRegression()
lr.fit(X1,Y)
print(lr.intercept_)
lr.coef_

[ 1.]


array([[ 1.,  1.]])

In [32]:
((X1.T*X1).I)*(X1.T)*Y

ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

In [26]:
X1=np.mat(X1)
Y=np.mat(Y)