In [6]:
import numpy as np
import pandas as pd
import matplotlib as mpl
from sklearn.preprocessing import PolynomialFeatures,StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
## 设置字符集，防止中文乱码
mpl.rcParams['font.sans-serif']=[u'simHei']
mpl.rcParams['axes.unicode_minus']=False

In [45]:
#定义一个简单的数据，使得数据符合y=x1+x2
df = pd.DataFrame({'x1':[1,2,3,4,5,6],'x2':[1,2,1,2,1,2],'y':[2,4,4,6,6,8],'y1':[4,8,8,12,12,16]})
x = df[['x1','x2']].values.reshape(-1,2)
y = df['y'].values.reshape([-1,1])
y1 = df['y1'].values.reshape([-1,1])
#print(x)
#print(y)

In [4]:
#使用直接计算法
import math
np.dot(np.mat(x.T.dot(x)).I,x.T).dot(y1)

matrix([[ 2.],
        [ 2.]])

In [16]:
#使用LinearRegression方法
lr=LinearRegression()
lr.fit(x,y)
print(lr.score(x,y))
print(lr.coef_)
print(lr.intercept_)

1.0
[[ 1.  1.]]
[  8.88178420e-16]


In [84]:
#使用梯度下降法
def gradient_descent(X,Y,theta,alpha):
    #print(X.dot(theta))
    #print(Y)
    theta=theta-alpha*X.T.dot(X.dot(theta)-Y)
    loss=0.5*((X.dot(theta)-Y)**2).sum()
    return theta,loss
    

In [71]:
#批量梯度下降
X=x
X=np.hstack((common_item,X))
Y=y
m,n=X.shape
#print(m,n)
alpha=0.01
theta=np.zeros((n,1)).reshape(-1,1).astype('f')
the=1e-06
max_iter=400
common_item=np.ones((m,1)).reshape(-1,1)
for t in range(max_iter):
    #print(X)
    #print(Y)
    theta,loss=gradient_descent(X,Y,theta,alpha)
    if loss<the:
        break
print(theta)
print(loss)

[[ 0.08243137]
 [ 0.99673148]
 [ 0.95651534]]
0.00182455127571


In [29]:
np.hstack?

In [90]:
#随机梯度下降
X=x
X=np.hstack((common_item,X))
Y=y
m,n=X.shape
print(m,n)
alpha=0.01
theta=np.zeros((n,1)).reshape(-1,1).astype('f')
the=1e-06
max_iter=400
common_item=np.ones((m,1)).reshape(-1,1)
for t in range(max_iter):
    for i in range(m):
        X1=X[i].reshape(1,-1)
        Y1=Y[i]
        theta,loss=gradient_descent(X1,Y1,theta,alpha)
        if loss<the:
            break
    if loss<the:
        break
print(theta)
print(loss)

6 3
[[ 0.32696342]
 [ 1.06927269]
 [ 0.60248703]]
8.15183439391e-07


In [98]:
#少批量梯度下降
X=x
X=np.hstack((common_item,X))
Y=y
m,n=X.shape
print(m,n)
alpha=0.01
theta=np.zeros((n,1)).reshape(-1,1).astype('f')
the=1e-06
max_iter=4000
common_item=np.ones((m,1)).reshape(-1,1)
d=2
for t in range(max_iter):
    for i in range(int(np.floor(m/2))):
        X1=X[i*d:d*(i+1)]
        Y1=Y[i*d:d*(i+1)]
        theta,loss=gradient_descent(X1,Y1,theta,alpha)
        if loss<the:
            break
    if loss<the:
        break
print(theta)
print(loss)

6 3
[[ 0.00350904]
 [ 0.99988504]
 [ 0.99812199]]
9.96555775854e-07


# 下面的程序有问题

In [139]:
#数据校验
#X是二维数组，Y是二维数组
def validata(X, Y):
    if X.shape[0]!=Y.shape[0]:
        return False
    else:
        return True

#批量梯度下降,
#返回新的theta值
def BGD(X,Y,theta,alpha):
    #print("theta:"+str(theta))
    #print(np.dot(X.T,X.dot(theta)-Y))
    theta=theta-alpha*np.dot(X.T,X.dot(theta)-Y)
    return theta

#随机梯度下降
def SGD(X,Y,theta,alpha):
    pass

#小批量梯度下降
def MBGD(X,Y,theta,alpha,num):
    pass


In [3]:
#fit函数
def fittt(X, Y, alphas, threshold=1e-6, maxIter=20, addConstantItem=True, theta=None):
    X_row_len=X.shape[0]
    ConstantItem=np.ones((X_row_len,1))
    if addConstantItem:#加上常数项
        X=np.hstack((X,ConstantItem))

    if np.logical_not(validata(X, Y)):
        print("erro params!")
        return

    X_col_len = X.shape[1]
    J=[np.NAN for i in alphas]
    for index,a in enumerate(alphas):
        ## 对当前的alpha进行梯度算法求解
        theta=np.zeros((X_col_len,1))#初始化theta
        J[index]=((X.dot(theta)-Y)**2).sum()
        for times in range(maxIter):
            #print(theta)
            print(J[index])
            theta=BGD(X,Y,theta,a)
            J[index]=((X.dot(theta)-Y)**2).sum()
            if J[index]<=threshold:
                break
    #print(J)

In [217]:
## 创建模拟数据
np.random.seed(0)
N = 10
X = np.arange(1,5)
#X = np.linspace(0, 6, N) + np.random.randn(N)
Y = X**3 + X**2 -X - 7
X = X.reshape(-1, 1)
Y = Y.reshape(-1, 1)
#poly=PolynomialFeatures(degree=3)
#X=poly.fit_transform(X)
ss=StandardScaler()
#X=ss.fit_transform(X)
X1=np.array([[1.,1.,1.,1.],
 [1.,2.,4.,8.],
 [1.,3.,9.,27.],
 [1.,4.,16.,64.]])
X1=ss.fit_transform(X1)
#X1=X1[:,[1]]
Y1=np.array([[-6],
 [ 3],
 [26],
 [69]])
print(X1)
print(Y1)

[[ 0.         -1.34164079 -1.14458618 -0.98184354]
 [ 0.         -0.4472136  -0.61631563 -0.69547251]
 [ 0.          0.4472136   0.26413527  0.08182029]
 [ 0.          1.34164079  1.49676654  1.59549575]]
[[-6]
 [ 3]
 [26]
 [69]]


In [5]:
fittt(X1, Y1, [0.01], threshold=1e-6, maxIter=20, addConstantItem=False, theta=None)

NameError: name 'X1' is not defined

In [147]:
PolynomialFeatures?

In [6]:
for 
theta=theta-alpha*np.dot(X.T,X.dot(theta)-Y)

SyntaxError: invalid syntax (<ipython-input-6-7997a16ff19f>, line 1)

In [7]:
maxIter=100
alpha = 0.0001
theta=np.array([-0.1,-0.1,0.1,0.2]).reshape(-1,1)
#print(theta)
threshold = 1e-3
for times in range(maxIter):
    print(theta)
    print(X1.T.dot(Y1-X1.dot(theta)))
    theta = theta - alpha * X1.T.dot(Y1-X1.dot(theta))
    J = np.power(Y1-X1.dot(theta),2).sum()
    print(J)
    if J<=threshold:
        break

[[-0.1]
 [-0.1]
 [ 0.1]
 [ 0.2]]


NameError: name 'X1' is not defined